#!/bin/zsh

# ------------------------------------------------------------------------------
# FUNCTIONS
# ------------------------------------------------------------------------------

integer SELECTED=1
OPTIONS=()
OPTIONS_SANE=()
get_options() {

    SELECTED+=$(pacmd list-sinks | grep -Po '(?<=\* index:\s)\d+')

    # Elements appended to array lost after funciton is done in Bash, hence why
    # this requires Zsh

    pacmd list-sinks | grep -Po '(?<=name:\s<).*(?=>)' | while read line
    do
        OPTIONS+=( "$line" )
    done

    pacmd list-sinks | grep -Po '(?<=device\.description =\s").*(?=")' | while read line
    do
        OPTIONS_SANE+=( "$line" )
    done

}

# ------------------------------------------------------------------------------
# MAIN CODE
# ------------------------------------------------------------------------------

get_options

USER_SELECTED=$(
    yad --mouse --height 120 --num-output --text "Choose Audio Sink" --entry "${OPTIONS_SANE[@]}" --entry-text "${OPTIONS_SANE[SELECTED]}"
)
! [ -z "$USER_SELECTED" ] && pactl set-default-sink "${OPTIONS[USER_SELECTED]}"